[build]
  base = "frontend"
  publish = "dist"
  functions = "backend/functions"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions]
  directory = "../backend/functions"
  external_node_modules = ["ethers", "@requestnetwork/request-client.js"]

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200